### ISSUE TITLE
ECS - EBS size problem 

### ISSUE THREAD

**Issue by neugeeug** [TeliaSoneraNorge/telia-terraform-modules#44]
I use r4.xlarge. I've deployed several services to ECS and with next one have got error:

`2018-05-18T14:51:49Z [WARN] DockerGoClient: failed to pull image 456893923059.dkr.ecr.eu-west-1.amazonaws.com/customercheckhandler-app:2.1.171: failed to register layer: devmapper: Thin Pool has 4359 free data blocks which is less than minimum required 4449 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior `

Below report from EC2 instances:

```
[ec2-user@ip-10-202-0-13 ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7,5G  112K  7,5G   1% /dev
tmpfs           7,5G     0  7,5G   0% /dev/shm
/dev/xvda1      7,8G  877M  6,8G  12% /

[ec2-user@ip-10-202-1-191 ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7,5G  116K  7,5G   1% /dev
tmpfs           7,5G     0  7,5G   0% /dev/shm
/dev/xvda1      7,8G  876M  6,8G  12% /
[ec2-user@ip-10-202-1-191 ~]$ 

[ec2-user@ip-10-202-2-224 ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7,5G  124K  7,5G   1% /dev
tmpfs           7,5G     0  7,5G   0% /dev/shm
/dev/xvda1      7,8G  877M  6,8G  12% /
[ec2-user@ip-10-202-2-224 ~]$ 

```
In my opinion EBS size should be added as parameter to ECS module. 
See also https://docs.aws.amazon.com/AmazonECS/latest/developerguide/CannotCreateContainerError.html

**Comment by itsdalmo** [comment]
Sounds good! Do you have time to submit a PR?

**Comment by neugeeug** [comment]
To be honest lots of other tasks and deadline is approaching ...

**Comment by mikael-lindstrom** [comment]
PR #57 is now merged and you can set `instance_volume_size`, could you check if this solved you issue?

**Comment by neugeeug** [comment]
Thanks. I will check it.

**Comment by neugeeug** [comment]
It seems that it works ok. Thanks
